# dtype = {
#     '[QUOTE_UNIXTIME]': 'uint32', 
#     ' [QUOTE_READTIME]': 'datetime64[ns]', 
#     ' [QUOTE_DATE]': 'datetime64[ns]', 
#     ' [QUOTE_TIME_HOURS]': 'float16', 
#     ' [UNDERLYING_LAST]': 'float16', 
#     ' [EXPIRE_DATE]': 'datetime64[ns]', 
#     ' [EXPIRE_UNIX]': 'uint32', 
#     ' [DTE]': 'float16', 
#     ' [C_DELTA]': 'float16', 
#     ' [C_GAMMA]': 'float16', 
#     ' [C_VEGA]': 'float16', 
#     ' [C_THETA]': 'float16', 
#     ' [C_RHO]': 'float16', 
#     ' [C_IV]': 'float16', 
#     ' [C_VOLUME]': 'float32', 
#     ' [C_LAST]': 'float16', 
#     ' [C_SIZE]': 'string', 
#     ' [C_BID]': 'float16', 
#     ' [C_ASK]': 'float16', 
#     ' [STRIKE]': 'float16', 
#     ' [P_BID]': 'float16', 
#     ' [P_ASK]': 'float16', 
#     ' [P_SIZE]': 'string', 
#     ' [P_LAST]': 'float16', 
#     ' [P_DELTA]': 'float16', 
#     ' [P_GAMMA]': 'float32', 
#     ' [P_VEGA]': 'float16', 
#     ' [P_THETA]': 'float16', 
#     ' [P_RHO]': 'float16', 
#     ' [P_IV]': 'float16', 
#     ' [P_VOLUME]': 'float32', 
#     ' [STRIKE_DISTANCE]': 'float16', 
#     ' [STRIKE_DISTANCE_PCT]': 'float16' 
# }

dtype = {
    '[QUOTE_UNIXTIME]': 'uint32', 
    ' [QUOTE_READTIME]': 'datetime64[ns]', 
    ' [QUOTE_DATE]': 'datetime64[ns]', 
    ' [QUOTE_TIME_HOURS]': 'float64', 
    ' [UNDERLYING_LAST]': 'float64', 
    ' [EXPIRE_DATE]': 'datetime64[ns]', 
    ' [EXPIRE_UNIX]': 'uint32', 
    ' [DTE]': 'float64', 
    ' [C_DELTA]': 'float64', 
    ' [C_GAMMA]': 'float64', 
    ' [C_VEGA]': 'float64', 
    ' [C_THETA]': 'float64', 
    ' [C_RHO]': 'float64', 
    ' [C_IV]': 'float64', 
    ' [C_VOLUME]': 'float64', 
    ' [C_LAST]': 'float64', 
    ' [C_SIZE]': 'string', 
    ' [C_BID]': 'float64', 
    ' [C_ASK]': 'float64', 
    ' [STRIKE]': 'float64', 
    ' [P_BID]': 'float64', 
    ' [P_ASK]': 'float64', 
    ' [P_SIZE]': 'string', 
    ' [P_LAST]': 'float64', 
    ' [P_DELTA]': 'float64', 
    ' [P_GAMMA]': 'float64', 
    ' [P_VEGA]': 'float64', 
    ' [P_THETA]': 'float64', 
    ' [P_RHO]': 'float64', 
    ' [P_IV]': 'float64', 
    ' [P_VOLUME]': 'float64', 
    ' [STRIKE_DISTANCE]': 'float64', 
    ' [STRIKE_DISTANCE_PCT]': 'float64' 
}

col_num = {
    '[QUOTE_UNIXTIME]': 0, 
    ' [QUOTE_READTIME]': 1, 
    ' [QUOTE_DATE]': 2, 
    ' [QUOTE_TIME_HOURS]': 3, 
    ' [UNDERLYING_LAST]': 4, 
    ' [EXPIRE_DATE]': 5, 
    ' [EXPIRE_UNIX]': 6, 
    ' [DTE]': 7, 
    ' [C_DELTA]': 8, 
    ' [C_GAMMA]': 9, 
    ' [C_VEGA]': 10, 
    ' [C_THETA]': 11, 
    ' [C_RHO]': 12, 
    ' [C_IV]': 13, 
    ' [C_VOLUME]': 14, 
    ' [C_LAST]': 15, 
    ' [C_SIZE]': 16, 
    ' [C_BID]': 17, 
    ' [C_ASK]': 18, 
    ' [STRIKE]': 19, 
    ' [P_BID]': 20, 
    ' [P_ASK]': 21, 
    ' [P_SIZE]': 22, 
    ' [P_LAST]': 23, 
    ' [P_DELTA]': 24, 
    ' [P_GAMMA]': 25, 
    ' [P_VEGA]': 26, 
    ' [P_THETA]': 27, 
    ' [P_RHO]': 28, 
    ' [P_IV]': 29, 
    ' [P_VOLUME]': 30, 
    ' [STRIKE_DISTANCE]': 31, 
    ' [STRIKE_DISTANCE_PCT]': 32 
}

description = {
    '[QUOTE_UNIXTIME]': 'Option Quote Time in UNIX Time', 
    ' [QUOTE_READTIME]': 'Option Quote Time in Readable Format', 
    ' [QUOTE_DATE]': 'Option Quote Date in Readable Format', 
    ' [QUOTE_TIME_HOURS]': 'Option Quote Hour', 
    ' [UNDERLYING_LAST]': 'Stock Last Traded Price', 
    ' [EXPIRE_DATE]': 'Option Expiry Date in Readable Format', 
    ' [EXPIRE_UNIX]': 'Option Expiry Time in UNIX Time', 
    ' [DTE]': 'Option Days To Expiration', 
    ' [C_DELTA]': 'Call Option Greeks - Delta', 
    ' [C_GAMMA]': 'Call Option Greeks - Gamma', 
    ' [C_VEGA]': 'Call Option Greeks - Vega', 
    ' [C_THETA]': 'Call Option Greeks - Theta', 
    ' [C_RHO]': 'Call Option Greeks - Rho', 
    ' [C_IV]': 'Call Option Implied Volatility', 
    ' [C_VOLUME]': 'Call Option Volume', 
    ' [C_LAST]': 'Call Option Last Traded Price', 
    ' [C_SIZE]': 'Call Option Size', 
    ' [C_BID]': 'Call Option Bid Price', 
    ' [C_ASK]': 'Call Option Ask Price', 
    ' [STRIKE]': 'Strike Price', 
    ' [P_BID]': 'Put Option Bid Price', 
    ' [P_ASK]': 'Put Option Ask Price', 
    ' [P_SIZE]': 'Put Option Size', 
    ' [P_LAST]': 'Put Option Last Traded Price', 
    ' [P_DELTA]': 'Put Option Greeks - Delta', 
    ' [P_GAMMA]': 'Put Option Greeks - Gamma', 
    ' [P_VEGA]': 'Put Option Greeks - Vega', 
    ' [P_THETA]': 'Put Option Greeks - Theta', 
    ' [P_RHO]': 'Put Option Greeks - Rho', 
    ' [P_IV]': 'Put Option Implied Volatility', 
    ' [P_VOLUME]': 'Put Option Volume', 
    ' [STRIKE_DISTANCE]': '', 
    ' [STRIKE_DISTANCE_PCT]': '' 
}